apiVersion: v1
kind: Service
metadata:
  name: cozserver-service
  namespace: default
spec:
  selector:
    color: blue # 구버전을 바라본다.
  type: LoadBalancer
  ports:
  - name: cozserver
    protocol: TCP
    port: 8080
    targetPort: 8080
