apiVersion: apps/v1
kind: Deployment
metadata:
  name: cozserver-canary
  labels:
    app: cozserver
    track: canary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cozserver
  template:
    metadata:
      labels:
        app: cozserver
    spec:
      containers:
      - name: cozserver
        image: sebcontents/cozserver:2.0 #신버전
        ports:
        - containerPort: 8080
