apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
  labels:
    app: cozserver
spec:
  type: NodePort
  selector:
    app: cozserver
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008